### PR TITLE
Added CI 

### PR DESCRIPTION
**Pull request by dblock**
I'm trying to add CI to this project, with some limited success.

1. Looks like there's some randomized testing infrastructure that requires disabling surefire tests? I am not familiar with this, but couldn't figure out how to properly enable tests without changing `skipTests`, or run them with the current configuration.
2. In GHA tests run successfully but there's a failure on cleanup (?), see https://github.com/dblock/opensearch-analysis-vietnamese/runs/6179138320?check_suite_focus=true. I wasn't able to fix this.

Could use a bit of help!

Signed-off-by: dblock <dblock@amazon.com>

### CODE REVIEW

**Comment by duydo** [comment]
@dblock It looks like the surefire plugin requires read/write permission for java.util.PropertyPermission. 
Let me investigate and fix that.

**Comment by duydo** [comment]
@dblock I tested with `maven-surefire-plugin` version `2.20` and it works. Can you try to use surefire plugin v2.20 instead of 2.22.0?

**Comment by duydo** [comment]
@dblock I fixed the issue and upgraded the plugin to OpenSearch version 1.3.2, you can sync the code and test it again.

**Comment by dblock** [comment]
Made more changes and have a passing build in https://github.com/dblock/opensearch-analysis-vietnamese/runs/6577807852?check_suite_focus=true.

**Comment by dblock** [comment]
With JDK 11 and 17: https://github.com/dblock/opensearch-analysis-vietnamese/actions/runs/2379406773

**Pull request merged**
